### ISSUE TITLE
Add a `Project.TOML` to the repo

### ISSUE THREAD

**Issue by Leticia-maria** [JuliaMolSim/MolSSI_workshop#4]
Add all the packages that will be required.

**Comment by rkurchin** [comment]
Yeah if you guys can just each start adding packages as you're developing your content, then as was discussed today, we can just use it as a demo for instantiating an environment from a file as well – e.g. install a few packages "manually" in base and/or other custom environment to know how to do that, and then use this to demonstrate how to install packages from a file (analogous to `environment.yaml` in conda) to set up for the rest of the day.
